services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  metadata-service:
    build:
      context: .
      dockerfile: deployments/metadata.Dockerfile
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: deployments/gateway.Dockerfile
    environment:
      - METADATA_ADDR=metadata-service:50051
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
      - metadata-service
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped

  worker-service:
    build:
      context: .
      dockerfile: deployments/worker.Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    volumes:
      - ./downloads:/app/downloads
      - ./ytCookies.txt:/app/ytCookies.txt
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOTBmMDc0ZTcwMDRmYjljZjdlMDg5YmJlYzc4Njc1YWQiLCJ0IjoiN2M4NjRkYjktY2Q2Zi00MTY3LThmYTYtMWNjNTA3ZmQ3MDVkIiwicyI6IlpUYzRPV0V6TWpRdE9HVTNZaTAwWW1RMUxXSmtOMll0TnpBM01XSTFOVE0yTnpobSJ9
    command: tunnel --no-autoupdate run