// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/metadata.proto

// Имя пакета для Protobuf

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Входящий запрос (только ссылка)
type VideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRequest) Reset() {
	*x = VideoRequest{}
	mi := &file_api_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRequest) ProtoMessage() {}

func (x *VideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRequest.ProtoReflect.Descriptor instead.
func (*VideoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *VideoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Ответ от сервиса
type VideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,2,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Formats       []*Format              `protobuf:"bytes,4,rep,name=formats,proto3" json:"formats,omitempty"` // Массив доступных форматов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	mi := &file_api_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *VideoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoResponse) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *VideoResponse) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *VideoResponse) GetFormats() []*Format {
	if x != nil {
		return x.Formats
	}
	return nil
}

// Структура одного формата (качества)
type Format struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormatId      string                 `protobuf:"bytes,1,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	Resolution    string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`              // например "1080p"
	Ext           string                 `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext,omitempty"`                            // например "mp4"
	HasAudio      bool                   `protobuf:"varint,4,opt,name=has_audio,json=hasAudio,proto3" json:"has_audio,omitempty"` // есть ли звук в этом потоке
	HasVideo      bool                   `protobuf:"varint,5,opt,name=has_video,json=hasVideo,proto3" json:"has_video,omitempty"`
	FilesizeBytes int64                  `protobuf:"varint,6,opt,name=filesize_bytes,json=filesizeBytes,proto3" json:"filesize_bytes,omitempty"` // Размер в байтах
	AudioBitrate  float64                `protobuf:"fixed64,7,opt,name=audio_bitrate,json=audioBitrate,proto3" json:"audio_bitrate,omitempty"`   // Качество аудио (kbps)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Format) Reset() {
	*x = Format{}
	mi := &file_api_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Format) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Format) ProtoMessage() {}

func (x *Format) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Format.ProtoReflect.Descriptor instead.
func (*Format) Descriptor() ([]byte, []int) {
	return file_api_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *Format) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

func (x *Format) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *Format) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *Format) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

func (x *Format) GetHasVideo() bool {
	if x != nil {
		return x.HasVideo
	}
	return false
}

func (x *Format) GetFilesizeBytes() int64 {
	if x != nil {
		return x.FilesizeBytes
	}
	return 0
}

func (x *Format) GetAudioBitrate() float64 {
	if x != nil {
		return x.AudioBitrate
	}
	return 0
}

var File_api_proto_metadata_proto protoreflect.FileDescriptor

const file_api_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/metadata.proto\x12\bmetadata\" \n" +
	"\fVideoRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x92\x01\n" +
	"\rVideoResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12#\n" +
	"\rthumbnail_url\x18\x02 \x01(\tR\fthumbnailUrl\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12*\n" +
	"\aformats\x18\x04 \x03(\v2\x10.metadata.FormatR\aformats\"\xdd\x01\n" +
	"\x06Format\x12\x1b\n" +
	"\tformat_id\x18\x01 \x01(\tR\bformatId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x10\n" +
	"\x03ext\x18\x03 \x01(\tR\x03ext\x12\x1b\n" +
	"\thas_audio\x18\x04 \x01(\bR\bhasAudio\x12\x1b\n" +
	"\thas_video\x18\x05 \x01(\bR\bhasVideo\x12%\n" +
	"\x0efilesize_bytes\x18\x06 \x01(\x03R\rfilesizeBytes\x12#\n" +
	"\raudio_bitrate\x18\a \x01(\x01R\faudioBitrate2R\n" +
	"\x0fMetadataService\x12?\n" +
	"\fGetVideoInfo\x12\x16.metadata.VideoRequest\x1a\x17.metadata.VideoResponseB?Z=github.com/fcvf-jmail/yt-downloader/pkg/gen/metadata;metadatab\x06proto3"

var (
	file_api_proto_metadata_proto_rawDescOnce sync.Once
	file_api_proto_metadata_proto_rawDescData []byte
)

func file_api_proto_metadata_proto_rawDescGZIP() []byte {
	file_api_proto_metadata_proto_rawDescOnce.Do(func() {
		file_api_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_metadata_proto_rawDesc), len(file_api_proto_metadata_proto_rawDesc)))
	})
	return file_api_proto_metadata_proto_rawDescData
}

var file_api_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_metadata_proto_goTypes = []any{
	(*VideoRequest)(nil),  // 0: metadata.VideoRequest
	(*VideoResponse)(nil), // 1: metadata.VideoResponse
	(*Format)(nil),        // 2: metadata.Format
}
var file_api_proto_metadata_proto_depIdxs = []int32{
	2, // 0: metadata.VideoResponse.formats:type_name -> metadata.Format
	0, // 1: metadata.MetadataService.GetVideoInfo:input_type -> metadata.VideoRequest
	1, // 2: metadata.MetadataService.GetVideoInfo:output_type -> metadata.VideoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_metadata_proto_init() }
func file_api_proto_metadata_proto_init() {
	if File_api_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_metadata_proto_rawDesc), len(file_api_proto_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_metadata_proto_goTypes,
		DependencyIndexes: file_api_proto_metadata_proto_depIdxs,
		MessageInfos:      file_api_proto_metadata_proto_msgTypes,
	}.Build()
	File_api_proto_metadata_proto = out.File
	file_api_proto_metadata_proto_goTypes = nil
	file_api_proto_metadata_proto_depIdxs = nil
}
